//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarForceMIS.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public long GuardID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int HoursOfWork { get; set; }
    
        public virtual Guard Guard { get; set; }
    }
}
