//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarForceMIS.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public long ReportID { get; set; }
        public string Thru { get; set; }
        public string ThruPosition { get; set; }
        public string Subject { get; set; }
        public string Re { get; set; }
        public string Body { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
