//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarForceMIS.BLL.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public long GuardID { get; set; }
        public long PositionID { get; set; }
        public long ScheduleID { get; set; }
        public long TourOfDutyID { get; set; }
    
        public virtual Guard Guard { get; set; }
        public virtual ScheduleLookUp ScheduleLookUp { get; set; }
        public virtual TourOfDutyLookUp TourOfDutyLookUp { get; set; }
        public virtual Position Position { get; set; }
    }
}
